server:
  mode: dev         # 应用程序运行模式（dev开发环境、test测试环境、prod线上环境）
  host: 0.0.0.0     # 服务器IP地址，默认使用0.0.0.0
  name: go-walker      # 服务名称
  port: 7788       # 服务端口号
logger:             # 日志配置
  level: debug # 级别
  prefix:    # 日志前缀
  format:  # 输出
  director: temp/log      # 日志文件夹
  encode-level: LowercaseColorLevelEncoder # 编码级
  stacktrace-key: # 栈名
  max-age: 168                         # 日志留存时间 小时
  show-line: true # 显示行
  log-in-console: true # 输出控制台
jwt:                # JWT配置
  sign-key: 56n1KywHIPEkWWIxffGpp8Dfl3z5SjE5WBeDStc1T64klnpoAqHrHN01vnete123   # Token密钥
  expires: 10080    # Token过期时长（单位：分钟）
  refresh: 14400    # Token 刷新时长（单位：分钟）
cache:              # 缓存配置
  type: redis
  addr: localhost:6379    # Redis服务器地址
  password:              # Redis密码
  db: 5                       # Redis数据库索引
dbs: # 数据库配置
  - master:
#      disable: true
      driver: mysql                                                       # 数据库类型（mysql, sqlite3, postgres, sqlserver）
      dns: root:123456@tcp(127.0.0.1:3306)/test?charset=utf8&parseTime=True&loc=Local&timeout=1000ms  # 数据库连接字符串
#      prefix: 日志前缀
      singular: false #全局复数
      max-idle-conns: 10 #最大空闲连接数 默认10
      max-open-conns: 30 #最大打开数
      max-lifetime: 60 #链接重置时间（分）
      log-mode: info #日志类型
      log-zap: true #是否通过zap写入日志文件
extend:             # 扩展项（此处没有提供具体说明）
  authBaseUrl: http://localhost:8000
    