app:
  server:
    mode: dev         # 应用程序运行模式（dev开发环境、test测试环境、prod线上环境）
    host: 0.0.0.0     # 服务器IP地址，默认使用0.0.0.0
    name: go-walker      # 服务名称
    port: 28000       # 服务端口号
  logger:             # 日志配置
    path: temp/logs    # 日志存放路径
    stdout: ''         # 日志输出方式（file：文件，default：命令行），此处为空表示不输出到命令行
    level: trace       # 日志等级（trace, debug, info, warn, error, fatal）
    enableddb: false   # 数据库日志开关
  jwt:                # JWT配置
    secret: 5n1KywHIPEkWWIxffGpp8Dfl3z5SjE5WBeDStc1T64klnpoAqHrHN01vneteCZG4   # Token密钥
    timeout: 604800    # Token过期时间（单位：秒）
  dbs:           # 数据库配置
    - db:
      name: master
      driver: mysql                                                       # 数据库类型（mysql, sqlite3, postgres, sqlserver）
      source: root:root@tcp(192.168.0.191:3306)/go-admin?charset=utf8...  # 数据库连接字符串
  cache:              # 缓存配置
    redis:            # Redis缓存配置
      addr: 192.168.0.191:6379    # Redis服务器地址
      password: redis             # Redis密码
      db: 5                       # Redis数据库索引
  extend:             # 扩展项（此处没有提供具体说明）
    authBaseUrl: http://localhost:8000
      