definitions:
  dto.DemoDto:
    properties:
      age:
        type: integer
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        minLength: 6
        type: string
      re_password:
        type: string
    required:
    - email
    - name
    - password
    - re_password
    type: object
  models.Demo:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  resp.Resp:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
      reqId:
        type: string
    type: object
  utils.Cpu:
    properties:
      cores:
        type: integer
      cpus:
        items:
          type: number
        type: array
    type: object
  utils.Disk:
    properties:
      totalGb:
        type: integer
      totalMb:
        type: integer
      usedGb:
        type: integer
      usedMb:
        type: integer
      usedPercent:
        type: integer
    type: object
  utils.Os:
    properties:
      compiler:
        type: string
      goVersion:
        type: string
      goos:
        type: string
      numCpu:
        type: integer
      numGoroutine:
        type: integer
    type: object
  utils.Ram:
    properties:
      totalMb:
        type: integer
      usedMb:
        type: integer
      usedPercent:
        type: integer
    type: object
  utils.Server:
    properties:
      cpu:
        $ref: '#/definitions/utils.Cpu'
      disk:
        $ref: '#/definitions/utils.Disk'
      os:
        $ref: '#/definitions/utils.Os'
      ram:
        $ref: '#/definitions/utils.Ram'
    type: object
info:
  contact: {}
  description: 一个简单的脚手
  title: go-walker API
  version: V0.0.1
paths:
  /api/v1/demo/ping:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.DemoDto'
      responses:
        "200":
          description: '{"code": 200, "data": [...]}'
          schema:
            allOf:
            - $ref: '#/definitions/resp.Resp'
            - properties:
                data:
                  $ref: '#/definitions/models.Demo'
              type: object
      summary: Ping接口
      tags:
      - Demo
  /api/v1/init:
    get:
      description: init接口
      responses:
        "200":
          description: '{"code": 200, "data": [...]}'
          schema:
            allOf:
            - $ref: '#/definitions/resp.Resp'
            - properties:
                data:
                  type: string
              type: object
      summary: init接口
      tags:
      - Default
  /api/v1/ping:
    get:
      description: Ping接口
      responses:
        "200":
          description: '{"code": 200, "data": [...]}'
          schema:
            allOf:
            - $ref: '#/definitions/resp.Resp'
            - properties:
                data:
                  $ref: '#/definitions/utils.Server'
              type: object
      summary: Ping接口
      tags:
      - Default
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
